Formulario_Tipo_Ajax_UJS_search/config/routes.rb
Rails.application.routes.draw do
	resources :comments , only: [:index, :create] do
		resources :votes, only: :create
	end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Formulario_Tipo_Ajax_UJS_search/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Formulario_Tipo_Ajax_UJS_search/app/models/comment.rb
class Comment < ApplicationRecord
	has_many :votes
end

Formulario_Tipo_Ajax_UJS_search/app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :comment
end

Formulario_Tipo_Ajax_UJS_search/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Formulario_Tipo_Ajax_UJS_search/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
  	if params[:q].present?
  		@comments = Comment.where('content like ?', "%#{params[:q]}%")
  	else
  		@comments = Comment.all
  	end
  end

  def create
  	@comment = Comment.create(comment_params)
  end

  private def comment_params
  	params.require(:comment).permit(:content)
  end
end

Formulario_Tipo_Ajax_UJS_search/app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
  	@comment = Comment.find(params[:comment_id])
  	Vote.create!(comment: @comment)
  end
end

Formulario_Tipo_Ajax_UJS_search/app/helpers/application_helper.rb
module ApplicationHelper
end

Formulario_Tipo_Ajax_UJS_search/app/helpers/comments_helper.rb
module CommentsHelper
end

Formulario_Tipo_Ajax_UJS_search/app/helpers/votes_helper.rb
module VotesHelper
end

Formulario_Tipo_Ajax_UJS_search/app/views/comments/_comment.html.erb
<div id="comment-<%= comment.id %>"><%= comment.content %> 
<small id="votes-comment-<%= comment.id %>"><%= link_to comment.votes.count, comment_votes_path(comment), method: :post, remote: true %></small>
</div>

Formulario_Tipo_Ajax_UJS_search/app/views/comments/create.js.erb
$("#comments_text_output").append("<p> <%= @comment.content %> </p>");

Formulario_Tipo_Ajax_UJS_search/app/views/comments/index.html.erb
<iframe width="640" height="360" src="https://www.youtube.com/embed/1Ij4Wd8ISqM" frameborder="0" gesture="media" allowfullscreen></iframe>

<%= form_with model: Comment.new do |f|  %>
	<%= f.label :content %>
	<%= f.text_field :content %>
	<%= f.submit :enviar %>
	<%=  %>
<% end %>

<form action="<%= comments_path %>">
	<input name="q">
</form>

<div id = "comments_text_output">
	<table>
		<tbody>
			 <%= render @comments %>
		</tbody>
	</table>
</div>

<script>
	$("[name=q]").keyup(function(event) {
	    $.ajax({
			url: '<%= comments_path %>',
			type: 'GET',
			dataType: 'script',
			data: {q: $(this).val()},
		})
		.done(function() {
			console.log("success");
		})
		.fail(function() {
			console.log("error");
		})
		.always(function() {
			console.log("complete");
		});
		
	})
</script>

Formulario_Tipo_Ajax_UJS_search/app/views/comments/index.js.erb
$("#comments_text_output").html("<%= j render @comments %>");

Formulario_Tipo_Ajax_UJS_search/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AjaxOne_Form_Serialize</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Formulario_Tipo_Ajax_UJS_search/app/views/votes/create.js.erb
// var value = $("#votes-comment-<%= @comment.id %>").text();
// $("#votes-comment-<%= @comment.id %>").text(parseInt(value) + 1);
$("#comment-<%= @comment.id %>").html("<%= j render @comment %>")